### ISSUE TITLE
database export missing

### ISSUE THREAD

**Issue by paquettm** [Mujahc/Ecommerce_Assignment1_CorrectVersion#1]
Please add your database export so I can complete correcting this assignment.
Thank you!

**Comment by Mujahc** [comment]
Database? In assignment 1, arent we only using json to store and retrieve
data?

**Comment by Mujahc** [comment]
Sir, i believe it's the messages.txt where i retrieve and store data

**Comment by paquettm** [comment]
You are correct! I was correcting Assignment 2 and this repository was listed in the same time as that assignment. Apologies for the confusion.

**Comment by paquettm** [comment]
You are correct! I was correcting Assignment 2 and this repository was listed in the same time as that assignment. Apologies for the confusion
